export function getObjectsMock() {
   return {
      success: true,
      errcode: 0,
      errmsg: 'ok',
      time: 1721696923,
      sequence: 2,
      data_total: 334,
      data: [
         {
            name: 'cdt_aci_application',
            title: 'ACI Application Profile',
            poller: 'aci',
            inherits: null,
            id: 1,
         },
         {
            name: 'cdt_aci_bridge_domain',
            title: 'ACI Bridging Domain',
            poller: 'aci',
            inherits: null,
            id: 2,
         },
         {
            name: 'cdt_aci_cep',
            title: 'ACI Client Endpoint',
            poller: 'aci',
            inherits: null,
            id: 3,
         },
         {
            name: 'cdt_aci_epg',
            title: 'ACI Endpoint Groups',
            poller: 'aci',
            inherits: null,
            id: 4,
         },
         {
            name: 'cdt_aci_fault',
            title: 'ACI Fault',
            poller: 'aci',
            inherits: null,
            id: 5,
         },
         {
            name: 'cdt_aci_fault_summary',
            title: 'ACI Fault Summary',
            poller: 'aci',
            inherits: null,
            id: 6,
         },
         {
            name: 'cdt_aci_node',
            title: 'ACI Node',
            poller: 'aci',
            inherits: null,
            id: 7,
         },
         {
            name: 'cdt_aci_pod',
            title: 'ACI Pod',
            poller: 'aci',
            inherits: null,
            id: 8,
         },
         {
            name: 'cdt_aci_rscep_to_path_ep',
            title: 'ACI RS Client Endpoint to Path Endpoint',
            poller: 'aci',
            inherits: null,
            id: 9,
         },
         {
            name: 'cdt_aci_subnet',
            title: 'ACI Subnet',
            poller: 'aci',
            inherits: null,
            id: 10,
         },
         {
            name: 'cdt_aci_tenant',
            title: 'ACI Tenant',
            poller: 'aci',
            inherits: null,
            id: 11,
         },
         {
            name: 'cdt_aci_vrf',
            title: 'ACI Private Network',
            poller: 'aci',
            inherits: null,
            id: 12,
         },
         {
            name: 'cdt_apcon_port',
            title: 'Apcon Interface',
            poller: 'snmp',
            inherits: null,
            id: 13,
         },
         {
            name: 'cdt_appnav_cisco',
            title: 'Cisco APPNAV',
            poller: 'snmp',
            inherits: null,
            id: 14,
         },
         {
            name: 'cdt_bgp_peer',
            title: 'BGP Peer',
            poller: 'snmp',
            inherits: null,
            id: 15,
         },
         {
            name: 'cdt_bgp_peer_addr_family_prefix_cisco',
            title: 'BGP Peer Address Family Prefix - Cisco',
            poller: 'snmp',
            inherits: null,
            id: 16,
         },
         {
            name: 'cdt_bgp_peer_cisco',
            title: 'BGP Peer - Cisco',
            poller: 'snmp',
            inherits: ['cdt_bgp_peer'],
            id: 17,
         },
         {
            name: 'cdt_bgp_peer_juniper',
            title: 'BGP Peer - Juniper',
            poller: 'snmp',
            inherits: ['cdt_bgp_peer'],
            id: 18,
         },
         {
            name: 'cdt_bluecoat_proxy_client',
            title: 'Blue Coat - Proxy Clients',
            poller: 'snmp',
            inherits: null,
            id: 19,
         },
         {
            name: 'cdt_checkpoint_firewall',
            title: 'Checkpoint Firewall',
            poller: 'snmp',
            inherits: null,
            id: 20,
         },
         {
            name: 'cdt_checkpoint_vpn_sessions',
            title: 'Checkpoint VPN Sessions',
            poller: 'snmp',
            inherits: null,
            id: 21,
         },
         {
            name: 'cdt_cisco_activeDS0',
            title: 'Cisco Active DS0',
            poller: 'snmp',
            inherits: null,
            id: 22,
         },
         {
            name: 'cdt_cisco_call_stats',
            title: 'Cisco Call Stats',
            poller: 'snmp',
            inherits: null,
            id: 23,
         },
         {
            name: 'cdt_cisco_cb_qos_class_map_config',
            title: 'Cisco CB QoS Config - ClassMap',
            poller: 'snmp',
            inherits: null,
            id: 24,
         },
         {
            name: 'cdt_cisco_cb_qos_class_map_data',
            title: 'Cisco CB QoS Data - Class',
            poller: 'snmp',
            inherits: null,
            id: 25,
         },
         {
            name: 'cdt_cisco_cb_qos_config_policy_class',
            title: 'Cisco CB QoS Config - Policy/Class',
            poller: 'snmp',
            inherits: null,
            id: 26,
         },
         {
            name: 'cdt_cisco_cb_qos_match_data',
            title: 'Cisco CB QoS Data - Match',
            poller: 'snmp',
            inherits: null,
            id: 27,
         },
         {
            name: 'cdt_cisco_cb_qos_match_map_config',
            title: 'Cisco CB QoS Config - Match',
            poller: 'snmp',
            inherits: null,
            id: 28,
         },
         {
            name: 'cdt_cisco_cb_qos_policy_map_config',
            title: 'Cisco CB QoS Config - PolicyMap',
            poller: 'snmp',
            inherits: null,
            id: 29,
         },
         {
            name: 'cdt_cisco_cb_qos_queue_data',
            title: 'Cisco CB QoS Data - Queue',
            poller: 'snmp',
            inherits: null,
            id: 30,
         },
         {
            name: 'cdt_cisco_cb_qos_queue_map_config',
            title: 'Cisco CB QoS Config - Queue',
            poller: 'snmp',
            inherits: null,
            id: 31,
         },
         {
            name: 'cdt_cisco_cdp_cache',
            title: 'Cisco Discovery Protocol Cache',
            poller: 'snmp',
            inherits: null,
            id: 32,
         },
         {
            name: 'cdt_cisco_eigrp',
            title: 'Cisco EIGRP',
            poller: 'snmp',
            inherits: null,
            id: 33,
         },
         {
            name: 'cdt_cisco_eigrp_peer',
            title: 'Cisco EIGRP Peer',
            poller: 'snmp',
            inherits: null,
            id: 34,
         },
         {
            name: 'cdt_cisco_fan',
            title: 'Cisco Fan Monitoring',
            poller: 'snmp',
            inherits: null,
            id: 35,
         },
         {
            name: 'cdt_cisco_fib_tcam',
            title: 'Cisco TCAM Entries',
            poller: 'snmp',
            inherits: null,
            id: 36,
         },
         {
            name: 'cdt_cisco_firewall_connections',
            title: 'Cisco Firewall Connections',
            poller: 'snmp',
            inherits: null,
            id: 37,
         },
         {
            name: 'cdt_cisco_fru',
            title: 'Cisco FRU',
            poller: 'snmp',
            inherits: null,
            id: 38,
         },
         {
            name: 'cdt_cisco_if_extension',
            title: 'Cisco IF Extension',
            poller: 'snmp',
            inherits: null,
            id: 39,
         },
         {
            name: 'cdt_cisco_ipsec_global',
            title: 'Cisco VPN Global Tunnels',
            poller: 'snmp',
            inherits: null,
            id: 40,
         },
         {
            name: 'cdt_cisco_ipsec_tun',
            title: 'Cisco VPN Tunnels',
            poller: 'snmp',
            inherits: null,
            id: 41,
         },
         {
            name: 'cdt_cisco_ipsla',
            title: 'Cisco IPSLA',
            poller: 'snmp',
            inherits: null,
            id: 42,
         },
         {
            name: 'cdt_cisco_nbar',
            title: 'Cisco NBAR',
            poller: 'snmp',
            inherits: null,
            id: 43,
         },
         {
            name: 'cdt_cisco_vpn_profiles',
            title: 'Cisco VPN Profiles',
            poller: 'snmp',
            inherits: null,
            id: 44,
         },
         {
            name: 'cdt_cisco_vpn_sessions',
            title: 'Cisco VPN Sessions',
            poller: 'snmp',
            inherits: null,
            id: 45,
         },
         {
            name: 'cdt_cisco_wan_3g',
            title: 'Cisco WAN 3G',
            poller: 'snmp',
            inherits: null,
            id: 46,
         },
         {
            name: 'cdt_cisco_wan_3g_nearby_cells',
            title: 'Cisco WAN 3G Nearby Cells',
            poller: 'snmp',
            inherits: null,
            id: 47,
         },
         {
            name: 'cdt_cisco_wan_4g',
            title: 'Cisco WAN 4G',
            poller: 'snmp',
            inherits: null,
            id: 48,
         },
         {
            name: 'cdt_cisco_wsa_cache',
            title: 'Cisco WSA (Web Security Appliance)',
            poller: 'snmp',
            inherits: null,
            id: 49,
         },
         {
            name: 'cdt_citrix_netscaler_vpn_stats',
            title: 'Citrix Netscaler AAA Stats',
            poller: 'snmp',
            inherits: null,
            id: 50,
         },
         {
            name: 'cdt_connections_riverbed',
            title: 'Riverbed WAN Accelerator',
            poller: 'snmp',
            inherits: null,
            id: 51,
         },
         {
            name: 'cdt_cpu',
            title: 'CPU',
            poller: 'snmp',
            inherits: null,
            id: 52,
         },
         {
            name: 'cdt_cpu_alcatel',
            title: 'CPU - Alcatel',
            poller: 'snmp',
            inherits: ['cdt_cpu'],
            id: 53,
         },
         {
            name: 'cdt_cpu_alcatel_aos7',
            title: 'CPU - Alcatel - AOS7',
            poller: 'snmp',
            inherits: ['cdt_cpu'],
            id: 54,
         },
         {
            name: 'cdt_cpu_alteon',
            title: 'CPU - Alteon',
            poller: 'snmp',
            inherits: ['cdt_cpu'],
            id: 55,
         },
         {
            name: 'cdt_cpu_aruba',
            title: 'CPU - Aruba',
            poller: 'snmp',
            inherits: ['cdt_cpu'],
            id: 56,
         },
         {
            name: 'cdt_cpu_avaya_rc',
            title: 'CPU - Avaya RC',
            poller: 'snmp',
            inherits: ['cdt_cpu'],
            id: 57,
         },
         {
            name: 'cdt_cpu_avaya_s5',
            title: 'CPU - Avaya S5',
            poller: 'snmp',
            inherits: ['cdt_cpu'],
            id: 58,
         },
         {
            name: 'cdt_cpu_bluecoat',
            title: 'CPU - BlueCoat',
            poller: 'snmp',
            inherits: ['cdt_cpu'],
            id: 59,
         },
         {
            name: 'cdt_cpu_cisco',
            title: 'CPU - Cisco',
            poller: 'snmp',
            inherits: ['cdt_cpu'],
            id: 60,
         },
         {
            name: 'cdt_cpu_cisco_asa',
            title: 'CPU - Cisco ASA',
            poller: 'snmp',
            inherits: ['cdt_cpu_cisco', 'cdt_cpu'],
            id: 61,
         },
         {
            name: 'cdt_cpu_cisco_nexus',
            title: 'CPU - Cisco Nexus',
            poller: 'snmp',
            inherits: ['cdt_cpu'],
            id: 62,
         },
         {
            name: 'cdt_cpu_cisco_san',
            title: 'CPU - Cisco SAN',
            poller: 'snmp',
            inherits: ['cdt_cpu'],
            id: 63,
         },
         {
            name: 'cdt_cpu_cisco_wsa',
            title: 'CPU - Cisco WSA',
            poller: 'snmp',
            inherits: ['cdt_cpu'],
            id: 64,
         },
         {
            name: 'cdt_cpu_cisco_wsa_cache',
            title: 'CPU - Cisco WSA Cache',
            poller: 'snmp',
            inherits: ['cdt_cpu'],
            id: 65,
         },
         {
            name: 'cdt_cpu_dell',
            title: 'CPU - Dell',
            poller: 'snmp',
            inherits: ['cdt_cpu'],
            id: 66,
         },
         {
            name: 'cdt_cpu_dell_F10_S',
            title: 'CPU - Dell F10 S',
            poller: 'snmp',
            inherits: ['cdt_cpu'],
            id: 67,
         },
         {
            name: 'cdt_cpu_dell_dnos',
            title: 'CPU - Dell DNOS',
            poller: 'snmp',
            inherits: ['cdt_cpu'],
            id: 68,
         },
         {
            name: 'cdt_cpu_dell_x',
            title: 'CPU - Dell X Series',
            poller: 'snmp',
            inherits: ['cdt_cpu'],
            id: 69,
         },
         {
            name: 'cdt_cpu_extreme',
            title: 'CPU - Extreme',
            poller: 'snmp',
            inherits: ['cdt_cpu'],
            id: 70,
         },
         {
            name: 'cdt_cpu_extreme_vsp',
            title: 'CPU - Extreme VSP',
            poller: 'snmp',
            inherits: ['cdt_cpu'],
            id: 71,
         },
         {
            name: 'cdt_cpu_fortinet_fortigate',
            title: 'CPU - Fortinet Fortigate',
            poller: 'snmp',
            inherits: ['cdt_cpu'],
            id: 72,
         },
         {
            name: 'cdt_cpu_foundry',
            title: 'CPU - Foundry',
            poller: 'snmp',
            inherits: ['cdt_cpu'],
            id: 73,
         },
         {
            name: 'cdt_cpu_foundry_mlx',
            title: 'CPU - Foundry MLX',
            poller: 'snmp',
            inherits: ['cdt_cpu_foundry', 'cdt_cpu'],
            id: 74,
         },
         {
            name: 'cdt_cpu_freebsd',
            title: 'CPU - FreeBSD',
            poller: 'spe-proc-monitor',
            inherits: ['cdt_cpu'],
            id: 75,
         },
         {
            name: 'cdt_cpu_juniper',
            title: 'CPU - Juniper',
            poller: 'snmp',
            inherits: ['cdt_cpu'],
            id: 76,
         },
         {
            name: 'cdt_cpu_juniper_pulse',
            title: 'CPU - Juniper Pulse',
            poller: 'snmp',
            inherits: ['cdt_cpu'],
            id: 77,
         },
         {
            name: 'cdt_cpu_juniper_srx',
            title: 'CPU - Juniper SRX',
            poller: 'snmp',
            inherits: ['cdt_cpu'],
            id: 78,
         },
         {
            name: 'cdt_cpu_netscaler',
            title: 'CPU - NetScaler',
            poller: 'snmp',
            inherits: ['cdt_cpu'],
            id: 79,
         },
         {
            name: 'cdt_cpu_netscreen',
            title: 'CPU - Netscreen',
            poller: 'snmp',
            inherits: ['cdt_cpu'],
            id: 80,
         },
         {
            name: 'cdt_cpu_nokia',
            title: 'CPU - Nokia',
            poller: 'snmp',
            inherits: ['cdt_cpu'],
            id: 81,
         },
         {
            name: 'cdt_cpu_procurve',
            title: 'CPU - Procurve',
            poller: 'snmp',
            inherits: ['cdt_cpu'],
            id: 82,
         },
         {
            name: 'cdt_cpu_server',
            title: 'CPU - Server',
            poller: 'snmp',
            inherits: ['cdt_cpu'],
            id: 83,
         },
         {
            name: 'cdt_cpu_ucd',
            title: 'CPU - UCD',
            poller: 'snmp',
            inherits: ['cdt_cpu'],
            id: 84,
         },
         {
            name: 'cdt_cpu_viptela',
            title: 'CPU - Viptela',
            poller: 'snmp',
            inherits: ['cdt_cpu'],
            id: 85,
         },
         {
            name: 'cdt_dell_inventory',
            title: 'Dell DNOS System Information',
            poller: 'snmp',
            inherits: null,
            id: 86,
         },
         {
            name: 'cdt_device',
            title: 'Device',
            poller: 'snmp',
            inherits: null,
            id: 87,
         },
         {
            name: 'cdt_device_apic',
            title: 'APIC',
            poller: 'aci',
            inherits: ['cdt_device'],
            id: 88,
         },
         {
            name: 'cdt_device_freebsd',
            title: 'Device - FreeBSD',
            poller: 'spe-proc-monitor',
            inherits: ['cdt_device'],
            id: 89,
         },
         {
            name: 'cdt_device_oa',
            title: 'Observability Appliance',
            poller: 'oa',
            inherits: ['cdt_device_freebsd', 'cdt_device'],
            id: 90,
         },
         {
            name: 'cdt_dhcp_infoblox_scopes',
            title: 'Infoblox - DHCP',
            poller: 'snmp',
            inherits: null,
            id: 91,
         },
         {
            name: 'cdt_dhcp_infoblox_stats',
            title: 'Infoblox - DHCP Stats',
            poller: 'snmp',
            inherits: null,
            id: 92,
         },
         {
            name: 'cdt_dhcp_microsoft_scopes',
            title: 'DHCP Scopes - Microsoft',
            poller: 'snmp',
            inherits: null,
            id: 93,
         },
         {
            name: 'cdt_dhcp_microsoft_stats',
            title: 'DHCP Stats - Microsoft',
            poller: 'snmp',
            inherits: null,
            id: 94,
         },
         {
            name: 'cdt_diskio',
            title: 'Disk IO - FreeBSD',
            poller: 'spe-proc-monitor',
            inherits: null,
            id: 95,
         },
         {
            name: 'cdt_dns_infoblox_stats',
            title: 'Infoblox - DNS',
            poller: 'snmp',
            inherits: null,
            id: 96,
         },
         {
            name: 'cdt_dns_infoblox_zone',
            title: 'Infoblox - DNS - Zone',
            poller: 'snmp',
            inherits: null,
            id: 97,
         },
         {
            name: 'cdt_eip_dhcp',
            title: 'EIP DHCP',
            poller: 'snmp',
            inherits: null,
            id: 98,
         },
         {
            name: 'cdt_eip_dns',
            title: 'EIP DNS',
            poller: 'snmp',
            inherits: null,
            id: 99,
         },
         {
            name: 'cdt_env_mon',
            title: 'Environment Monitors',
            poller: 'snmp',
            inherits: null,
            id: 100,
         },
         {
            name: 'cdt_env_mon_apc_ems',
            title: 'APC Environment Management System',
            poller: 'snmp',
            inherits: ['cdt_env_mon'],
            id: 101,
         },
         {
            name: 'cdt_env_mon_apc_internal',
            title: 'APC Internal Environment Monitor',
            poller: 'snmp',
            inherits: ['cdt_env_mon'],
            id: 102,
         },
         {
            name: 'cdt_env_mon_enviromux_external_dewpoint',
            title: 'Enviromux Environmental Monitoring - External - Dew Point',
            poller: 'snmp',
            inherits: ['cdt_env_mon'],
            id: 103,
         },
         {
            name: 'cdt_env_mon_enviromux_external_humidity',
            title: 'Enviromux Environmental Monitoring - External - Humidity',
            poller: 'snmp',
            inherits: ['cdt_env_mon'],
            id: 104,
         },
         {
            name: 'cdt_env_mon_enviromux_external_temperature',
            title: 'Enviromux Environmental Monitoring - External - Temperature',
            poller: 'snmp',
            inherits: ['cdt_env_mon'],
            id: 105,
         },
         {
            name: 'cdt_env_mon_enviromux_internal_dewpoint',
            title: 'Enviromux Environmental Monitoring - Internal - Dew Point',
            poller: 'snmp',
            inherits: ['cdt_env_mon'],
            id: 106,
         },
         {
            name: 'cdt_env_mon_enviromux_internal_humidity',
            title: 'Enviromux Environmental Monitoring - Internal - Humidty',
            poller: 'snmp',
            inherits: ['cdt_env_mon'],
            id: 107,
         },
         {
            name: 'cdt_env_mon_enviromux_internal_temperature',
            title: 'Enviromux Environmental Monitoring - Internal - Temperature',
            poller: 'snmp',
            inherits: ['cdt_env_mon'],
            id: 108,
         },
         {
            name: 'cdt_env_mon_geist_internal',
            title: 'Geist Internal Environment Monitor',
            poller: 'snmp',
            inherits: ['cdt_env_mon'],
            id: 109,
         },
         {
            name: 'cdt_env_mon_interseptor',
            title: 'Interseptor Environment Monitor',
            poller: 'snmp',
            inherits: ['cdt_env_mon'],
            id: 110,
         },
         {
            name: 'cdt_env_mon_vertiv',
            title: 'Vertiv Environmental Monitoring',
            poller: 'snmp',
            inherits: ['cdt_env_mon'],
            id: 111,
         },
         {
            name: 'cdt_f5_apm_sessions',
            title: 'F5 APM Sessions',
            poller: 'snmp',
            inherits: null,
            id: 112,
         },
         {
            name: 'cdt_f5_bigip_interface',
            title: 'F5 Big IP Monitoring',
            poller: 'snmp',
            inherits: null,
            id: 113,
         },
         {
            name: 'cdt_f5_firewall_connections',
            title: 'F5 Firewall Connections',
            poller: 'snmp',
            inherits: null,
            id: 114,
         },
         {
            name: 'cdt_f5_loadbalancer_ltm_pool',
            title: 'F5 Load Balancer LTM Pool',
            poller: 'snmp',
            inherits: null,
            id: 115,
         },
         {
            name: 'cdt_f5_loadbalancer_ltm_pool_member',
            title: 'F5 Load Balancer LTM Pool Member',
            poller: 'snmp',
            inherits: null,
            id: 116,
         },
         {
            name: 'cdt_f5_loadbalancer_ltm_virtual_server',
            title: 'F5 Load Balancer LTM Virtual Server',
            poller: 'snmp',
            inherits: null,
            id: 117,
         },
         {
            name: 'cdt_fan_sensor',
            title: 'Sensor - Fan',
            poller: 'snmp',
            inherits: null,
            id: 118,
         },
         {
            name: 'cdt_fan_sensor_cisco',
            title: 'Sensor - Fan - Cisco',
            poller: 'snmp',
            inherits: ['cdt_fan_sensor'],
            id: 119,
         },
         {
            name: 'cdt_fan_sensor_entity',
            title: 'Sensor - Fan - Entity',
            poller: 'snmp',
            inherits: ['cdt_fan_sensor'],
            id: 120,
         },
         {
            name: 'cdt_filesystem',
            title: 'File System',
            poller: 'snmp',
            inherits: null,
            id: 121,
         },
         {
            name: 'cdt_filesystem_freebsd',
            title: 'File System - FreeBSD',
            poller: 'spe-proc-monitor',
            inherits: ['cdt_filesystem'],
            id: 122,
         },
         {
            name: 'cdt_filesystem_hostres',
            title: 'File System - Host Resources',
            poller: 'snmp',
            inherits: ['cdt_filesystem'],
            id: 123,
         },
         {
            name: 'cdt_filesystem_informant',
            title: 'File System - SNMP Informant',
            poller: 'snmp',
            inherits: ['cdt_filesystem'],
            id: 124,
         },
         {
            name: 'cdt_fortigate_vpn_stats',
            title: 'Fortinet Fortigate VPN Stats',
            poller: 'snmp',
            inherits: null,
            id: 125,
         },
         {
            name: 'cdt_framerelay',
            title: 'Frame Relay',
            poller: 'snmp',
            inherits: null,
            id: 126,
         },
         {
            name: 'cdt_framerelay_cisco',
            title: 'Frame Relay - Cisco',
            poller: 'snmp',
            inherits: ['cdt_framerelay'],
            id: 127,
         },
         {
            name: 'cdt_framerelay_juniper',
            title: 'Frame Relay - Juniper',
            poller: 'snmp',
            inherits: ['cdt_framerelay'],
            id: 128,
         },
         {
            name: 'cdt_framerelay_nortel',
            title: 'Frame Relay - Nortel',
            poller: 'snmp',
            inherits: ['cdt_framerelay'],
            id: 129,
         },
         {
            name: 'cdt_fw_fortinet_fortigate',
            title: 'Fortinet Fortigate Firewall',
            poller: 'snmp',
            inherits: null,
            id: 130,
         },
         {
            name: 'cdt_hh3c_nqa',
            title: 'HH3C - NQA',
            poller: 'snmp',
            inherits: null,
            id: 131,
         },
         {
            name: 'cdt_host_resources',
            title: 'Host Statistics',
            poller: 'snmp',
            inherits: null,
            id: 132,
         },
         {
            name: 'cdt_ieee_80211',
            title: 'IEEE 802.11',
            poller: 'snmp',
            inherits: null,
            id: 133,
         },
         {
            name: 'cdt_inventory',
            title: 'Inventory',
            poller: 'snmp',
            inherits: null,
            id: 134,
         },
         {
            name: 'cdt_inventory_device',
            title: 'Device Information',
            poller: 'snmp',
            inherits: ['cdt_inventory'],
            id: 135,
         },
         {
            name: 'cdt_inventory_entity',
            title: 'Entity Asset Information',
            poller: 'snmp',
            inherits: ['cdt_inventory'],
            id: 136,
         },
         {
            name: 'cdt_inventory_f5',
            title: 'F5 Asset Information',
            poller: 'snmp',
            inherits: ['cdt_inventory'],
            id: 137,
         },
         {
            name: 'cdt_inventory_f5_chassis',
            title: 'F5 Chassis Information',
            poller: 'snmp',
            inherits: ['cdt_inventory_f5', 'cdt_inventory'],
            id: 138,
         },
         {
            name: 'cdt_inventory_f5_slot',
            title: 'F5 Slot Information',
            poller: 'snmp',
            inherits: ['cdt_inventory_f5', 'cdt_inventory'],
            id: 139,
         },
         {
            name: 'cdt_inventory_juniper',
            title: 'Juniper Asset Information',
            poller: 'snmp',
            inherits: ['cdt_inventory'],
            id: 140,
         },
         {
            name: 'cdt_inventory_riverbed',
            title: 'Riverbed Asset Information',
            poller: 'snmp',
            inherits: ['cdt_inventory'],
            id: 141,
         },
         {
            name: 'cdt_ip_addr',
            title: 'IP Address Table',
            poller: 'snmp',
            inherits: null,
            id: 142,
         },
         {
            name: 'cdt_ip_addr_freebsd',
            title: 'IP Address Table - FreeBSD',
            poller: 'spe-proc-monitor',
            inherits: ['cdt_ip_addr'],
            id: 143,
         },
         {
            name: 'cdt_ip_address',
            title: 'IP Address Table (includes IPv6)',
            poller: 'snmp',
            inherits: null,
            id: 144,
         },
         {
            name: 'cdt_ip_system_stats',
            title: 'IP System Stats',
            poller: 'snmp',
            inherits: null,
            id: 145,
         },
         {
            name: 'cdt_juniper_cos',
            title: 'Juniper CoS',
            poller: 'snmp',
            inherits: null,
            id: 146,
         },
         {
            name: 'cdt_juniper_cos_class',
            title: 'Juniper CoS Classes',
            poller: 'snmp',
            inherits: null,
            id: 147,
         },
         {
            name: 'cdt_juniper_firewall',
            title: 'Juniper Firewall',
            poller: 'snmp',
            inherits: null,
            id: 148,
         },
         {
            name: 'cdt_juniper_ping',
            title: 'Juniper Ping',
            poller: 'snmp',
            inherits: null,
            id: 149,
         },
         {
            name: 'cdt_juniper_pulse_vpn_users',
            title: 'Juniper Pulse VPN Users',
            poller: 'snmp',
            inherits: null,
            id: 150,
         },
         {
            name: 'cdt_juniper_rpm',
            title: 'Juniper RPM',
            poller: 'snmp',
            inherits: null,
            id: 151,
         },
         {
            name: 'cdt_loadbalancer_alteon_group',
            title: 'Alteon Group',
            poller: 'snmp',
            inherits: null,
            id: 152,
         },
         {
            name: 'cdt_loadbalancer_alteon_rserv',
            title: 'Alteon Real Servers',
            poller: 'snmp',
            inherits: null,
            id: 153,
         },
         {
            name: 'cdt_loadbalancer_alteon_vserv',
            title: 'Alteon Virtual Servers',
            poller: 'snmp',
            inherits: null,
            id: 154,
         },
         {
            name: 'cdt_memory',
            title: 'Memory',
            poller: 'snmp',
            inherits: null,
            id: 155,
         },
         {
            name: 'cdt_memory_alcatel',
            title: 'Memory - Alcatel',
            poller: 'snmp',
            inherits: ['cdt_memory'],
            id: 156,
         },
         {
            name: 'cdt_memory_alcatel_aos7',
            title: 'Memory - Alcatel - AOS7',
            poller: 'snmp',
            inherits: ['cdt_memory'],
            id: 157,
         },
         {
            name: 'cdt_memory_alteon',
            title: 'Memory - Alteon',
            poller: 'snmp',
            inherits: ['cdt_memory'],
            id: 158,
         },
         {
            name: 'cdt_memory_aruba',
            title: 'Memory - Aruba',
            poller: 'snmp',
            inherits: ['cdt_memory'],
            id: 159,
         },
         {
            name: 'cdt_memory_avaya_rc',
            title: 'Memory - Avaya - RC',
            poller: 'snmp',
            inherits: ['cdt_memory'],
            id: 160,
         },
         {
            name: 'cdt_memory_avaya_s5',
            title: 'Memory - Avaya - S5',
            poller: 'snmp',
            inherits: ['cdt_memory'],
            id: 161,
         },
         {
            name: 'cdt_memory_bluecoat',
            title: 'Memory - BlueCoat',
            poller: 'snmp',
            inherits: ['cdt_memory'],
            id: 162,
         },
         {
            name: 'cdt_memory_checkpoint',
            title: 'Memory - Checkpoint',
            poller: 'snmp',
            inherits: ['cdt_memory'],
            id: 163,
         },
         {
            name: 'cdt_memory_checkpoint_virtual',
            title: 'Memory - Checkpoint Swap',
            poller: 'snmp',
            inherits: ['cdt_memory'],
            id: 164,
         },
         {
            name: 'cdt_memory_cisco',
            title: 'Memory - Cisco',
            poller: 'snmp',
            inherits: ['cdt_memory'],
            id: 165,
         },
         {
            name: 'cdt_memory_cisco_nexus',
            title: 'Memory - Cisco Enhanced',
            poller: 'snmp',
            inherits: ['cdt_memory'],
            id: 166,
         },
         {
            name: 'cdt_memory_cisco_san',
            title: 'Memory - Cisco SAN',
            poller: 'snmp',
            inherits: ['cdt_memory'],
            id: 167,
         },
         {
            name: 'cdt_memory_cisco_wsa',
            title: 'Memory - Cisco - WSA',
            poller: 'snmp',
            inherits: ['cdt_memory'],
            id: 168,
         },
         {
            name: 'cdt_memory_dell',
            title: 'Memory - Dell',
            poller: 'snmp',
            inherits: ['cdt_memory'],
            id: 169,
         },
         {
            name: 'cdt_memory_dell_F10_S',
            title: 'Memory - Dell F10 S',
            poller: 'snmp',
            inherits: ['cdt_memory'],
            id: 170,
         },
         {
            name: 'cdt_memory_dell_dnos',
            title: 'Memory - Dell DNOS',
            poller: 'snmp',
            inherits: ['cdt_memory'],
            id: 171,
         },
         {
            name: 'cdt_memory_extreme',
            title: 'Memory - Extreme',
            poller: 'snmp',
            inherits: ['cdt_memory'],
            id: 172,
         },
         {
            name: 'cdt_memory_extreme_vsp',
            title: 'Memory - Extreme VSP',
            poller: 'snmp',
            inherits: ['cdt_memory'],
            id: 173,
         },
         {
            name: 'cdt_memory_f5_host',
            title: 'Memory - F5 Host',
            poller: 'snmp',
            inherits: ['cdt_memory'],
            id: 174,
         },
         {
            name: 'cdt_memory_f5_host_other',
            title: 'Memory - F5 Host Other',
            poller: 'snmp',
            inherits: ['cdt_memory'],
            id: 175,
         },
         {
            name: 'cdt_memory_f5_swap',
            title: 'Memory - F5 Swap',
            poller: 'snmp',
            inherits: ['cdt_memory'],
            id: 176,
         },
         {
            name: 'cdt_memory_f5_tmm',
            title: 'Memory - F5 TMM',
            poller: 'snmp',
            inherits: ['cdt_memory'],
            id: 177,
         },
         {
            name: 'cdt_memory_fortinet_fortigate',
            title: 'Memory - Fortinet Fortigate',
            poller: 'snmp',
            inherits: ['cdt_memory'],
            id: 178,
         },
         {
            name: 'cdt_memory_fortinet_fortigate_hd',
            title: 'Memory - Fortinet Fortigate Hard Disk',
            poller: 'snmp',
            inherits: ['cdt_memory'],
            id: 179,
         },
         {
            name: 'cdt_memory_fortinet_fortigate_lowmem',
            title: 'Memory - Fortinet Fortigate Low Mem',
            poller: 'snmp',
            inherits: ['cdt_memory'],
            id: 180,
         },
         {
            name: 'cdt_memory_foundry',
            title: 'Memory - Foundry',
            poller: 'snmp',
            inherits: ['cdt_memory'],
            id: 181,
         },
         {
            name: 'cdt_memory_foundry_mlx',
            title: 'Memory - Foundry MLX',
            poller: 'snmp',
            inherits: ['cdt_memory_foundry', 'cdt_memory'],
            id: 182,
         },
         {
            name: 'cdt_memory_freebsd',
            title: 'Memory - FreeBSD',
            poller: 'spe-proc-monitor',
            inherits: ['cdt_memory'],
            id: 183,
         },
         {
            name: 'cdt_memory_juniper',
            title: 'Memory - Juniper',
            poller: 'snmp',
            inherits: ['cdt_memory'],
            id: 184,
         },
         {
            name: 'cdt_memory_netscaler',
            title: 'Memory - NetScaler',
            poller: 'snmp',
            inherits: ['cdt_memory'],
            id: 185,
         },
         {
            name: 'cdt_memory_netscreen',
            title: 'Memory - Netscreen',
            poller: 'snmp',
            inherits: ['cdt_memory'],
            id: 186,
         },
         {
            name: 'cdt_memory_nokia',
            title: 'Memory - Nokia',
            poller: 'snmp',
            inherits: ['cdt_memory'],
            id: 187,
         },
         {
            name: 'cdt_memory_procurve',
            title: 'Memory - Procurve',
            poller: 'snmp',
            inherits: ['cdt_memory'],
            id: 188,
         },
         {
            name: 'cdt_memory_server',
            title: 'Memory - Server',
            poller: 'snmp',
            inherits: ['cdt_memory'],
            id: 189,
         },
         {
            name: 'cdt_memory_ucd_real',
            title: 'Memory - UCD - Real',
            poller: 'snmp',
            inherits: ['cdt_memory'],
            id: 190,
         },
         {
            name: 'cdt_memory_ucd_swap',
            title: 'Memory - UCD - Swap',
            poller: 'snmp',
            inherits: ['cdt_memory'],
            id: 191,
         },
         {
            name: 'cdt_memory_viptela',
            title: 'Memory - Viptela',
            poller: 'snmp',
            inherits: ['cdt_memory'],
            id: 192,
         },
         {
            name: 'cdt_memory_virtual',
            title: 'Memory - Virtual',
            poller: 'snmp',
            inherits: ['cdt_memory'],
            id: 193,
         },
         {
            name: 'cdt_memory_virtual_freebsd',
            title: 'Memory - Virtual - FreeBSD',
            poller: 'spe-proc-monitor',
            inherits: ['cdt_memory'],
            id: 194,
         },
         {
            name: 'cdt_meraki_client',
            title: 'Meraki Client',
            poller: 'spe-meraki-monitor',
            inherits: null,
            id: 195,
         },
         {
            name: 'cdt_meraki_client_application',
            title: 'Meraki Client Application',
            poller: 'spe-meraki-monitor',
            inherits: null,
            id: 196,
         },
         {
            name: 'cdt_meraki_device',
            title: 'Meraki Device',
            poller: 'spe-meraki-monitor',
            inherits: null,
            id: 197,
         },
         {
            name: 'cdt_meraki_network',
            title: 'Meraki Network',
            poller: 'spe-meraki-monitor',
            inherits: null,
            id: 198,
         },
         {
            name: 'cdt_meraki_organization',
            title: 'Meraki Organization',
            poller: 'spe-meraki-monitor',
            inherits: null,
            id: 199,
         },
         {
            name: 'cdt_meraki_port',
            title: 'Meraki Interface',
            poller: 'spe-meraki-monitor',
            inherits: null,
            id: 200,
         },
         {
            name: 'cdt_meraki_topology',
            title: 'Meraki Topology',
            poller: 'spe-meraki-monitor',
            inherits: null,
            id: 201,
         },
         {
            name: 'cdt_meraki_uplink',
            title: 'Meraki Uplink',
            poller: 'spe-meraki-monitor',
            inherits: null,
            id: 202,
         },
         {
            name: 'cdt_meraki_vpn',
            title: 'Meraki VPN',
            poller: 'spe-meraki-monitor',
            inherits: null,
            id: 203,
         },
         {
            name: 'cdt_meraki_wireless',
            title: 'Meraki Wireless',
            poller: 'spe-meraki-monitor',
            inherits: null,
            id: 204,
         },
         {
            name: 'cdt_mis',
            title: 'MAC/IP/Switch Port (Deprecated)',
            poller: 'mis',
            inherits: null,
            id: 205,
         },
         {
            name: 'cdt_optical',
            title: 'Optical Signal Monitoring',
            poller: 'snmp',
            inherits: null,
            id: 206,
         },
         {
            name: 'cdt_optical_adva',
            title: 'Optical Signal Monitoring - ADVA',
            poller: 'snmp',
            inherits: ['cdt_optical'],
            id: 207,
         },
         {
            name: 'cdt_optical_adva_measurement',
            title: 'Optical Signal Monitoring - ADVA - Loss',
            poller: 'snmp',
            inherits: null,
            id: 208,
         },
         {
            name: 'cdt_optical_aruba',
            title: 'Optical Signal Monitoring - Aruba',
            poller: 'snmp',
            inherits: ['cdt_optical'],
            id: 209,
         },
         {
            name: 'cdt_optical_hirschmann',
            title: 'Optical Signal Monitoring - Hirschmann',
            poller: 'snmp',
            inherits: ['cdt_optical'],
            id: 210,
         },
         {
            name: 'cdt_optical_hirschmann2',
            title: 'Optical Signal Monitoring - Hirschmann2',
            poller: 'snmp',
            inherits: ['cdt_optical'],
            id: 211,
         },
         {
            name: 'cdt_optical_moxa',
            title: 'Optical Signal Monitoring - MOXA',
            poller: 'snmp',
            inherits: ['cdt_optical'],
            id: 212,
         },
         {
            name: 'cdt_optical_nbs',
            title: 'Optical Signal Monitoring - NBS',
            poller: 'snmp',
            inherits: ['cdt_optical'],
            id: 213,
         },
         {
            name: 'cdt_optical_sensor_cisco',
            title: 'Sensor - Optical - Cisco',
            poller: 'snmp',
            inherits: null,
            id: 214,
         },
         {
            name: 'cdt_ospf',
            title: 'OSPF Neighbor Monitoring',
            poller: 'snmp',
            inherits: null,
            id: 215,
         },
         {
            name: 'cdt_ospf_if',
            title: 'OSPF Neighbor Interfaces',
            poller: 'snmp',
            inherits: null,
            id: 216,
         },
         {
            name: 'cdt_other_sensor',
            title: 'Sensor - Other',
            poller: 'snmp',
            inherits: null,
            id: 217,
         },
         {
            name: 'cdt_other_sensor_cisco',
            title: 'Sensor - Other - Cisco',
            poller: 'snmp',
            inherits: ['cdt_other_sensor'],
            id: 218,
         },
         {
            name: 'cdt_other_sensor_entity',
            title: 'Sensor - Other - Entity',
            poller: 'snmp',
            inherits: ['cdt_other_sensor'],
            id: 219,
         },
         {
            name: 'cdt_palo_alto_firewall_connections',
            title: 'Palo Alto Firewall Connections',
            poller: 'snmp',
            inherits: null,
            id: 220,
         },
         {
            name: 'cdt_palo_alto_firewall_connections_zone',
            title: 'Palo Alto Firewall Connections Zone Stats',
            poller: 'snmp',
            inherits: null,
            id: 221,
         },
         {
            name: 'cdt_palo_alto_ha',
            title: 'Palo Alto HA',
            poller: 'snmp',
            inherits: null,
            id: 222,
         },
         {
            name: 'cdt_palo_alto_vpn',
            title: 'Palo Alto VPN',
            poller: 'snmp',
            inherits: null,
            id: 223,
         },
         {
            name: 'cdt_ping',
            title: 'Ping',
            poller: 'ping',
            inherits: null,
            id: 224,
         },
         {
            name: 'cdt_poe_main',
            title: 'PoE Device',
            poller: 'snmp',
            inherits: null,
            id: 225,
         },
         {
            name: 'cdt_poe_main_cisco',
            title: 'PoE Device - Cisco',
            poller: 'snmp',
            inherits: ['cdt_poe_main'],
            id: 226,
         },
         {
            name: 'cdt_poe_port',
            title: 'PoE Interface',
            poller: 'snmp',
            inherits: null,
            id: 227,
         },
         {
            name: 'cdt_poe_port_cisco',
            title: 'PoE Interface - Cisco',
            poller: 'snmp',
            inherits: ['cdt_poe_port'],
            id: 228,
         },
         {
            name: 'cdt_port',
            title: 'Interface',
            poller: 'snmp',
            inherits: null,
            id: 229,
         },
         {
            name: 'cdt_port_etherlike',
            title: 'Interface EtherLike',
            poller: 'snmp',
            inherits: null,
            id: 230,
         },
         {
            name: 'cdt_port_freebsd',
            title: 'Interface - FreeBSD',
            poller: 'spe-proc-monitor',
            inherits: ['cdt_port'],
            id: 231,
         },
         {
            name: 'cdt_port_nbar',
            title: 'Interface - Cisco NBAR',
            poller: 'snmp',
            inherits: null,
            id: 232,
         },
         {
            name: 'cdt_power_amps_sensor',
            title: 'Sensor - Power - Amps',
            poller: 'snmp',
            inherits: null,
            id: 233,
         },
         {
            name: 'cdt_power_amps_sensor_cisco',
            title: 'Sensor - Power - Amps - Cisco',
            poller: 'snmp',
            inherits: ['cdt_power_amps_sensor'],
            id: 234,
         },
         {
            name: 'cdt_power_amps_sensor_entity',
            title: 'Sensor - Power - Amps - Entity',
            poller: 'snmp',
            inherits: ['cdt_power_amps_sensor'],
            id: 235,
         },
         {
            name: 'cdt_power_system_battery',
            title: 'Power Systems - Battery',
            poller: 'snmp',
            inherits: null,
            id: 236,
         },
         {
            name: 'cdt_power_system_battery_alpha',
            title: 'Power Systems Battery - Alpha Power',
            poller: 'snmp',
            inherits: ['cdt_power_system_battery'],
            id: 237,
         },
         {
            name: 'cdt_power_system_battery_apcups',
            title: 'Power Systems Battery - APC Schneider Electric UPS',
            poller: 'snmp',
            inherits: ['cdt_power_system_battery'],
            id: 238,
         },
         {
            name: 'cdt_power_system_battery_generic_ups',
            title: 'Power Systems Battery - Generic UPS',
            poller: 'snmp',
            inherits: ['cdt_power_system_battery'],
            id: 239,
         },
         {
            name: 'cdt_power_system_input',
            title: 'Power Systems - Input',
            poller: 'snmp',
            inherits: null,
            id: 240,
         },
         {
            name: 'cdt_power_system_input_alpha',
            title: 'Power Systems Input - Alpha Power',
            poller: 'snmp',
            inherits: ['cdt_power_system_input'],
            id: 241,
         },
         {
            name: 'cdt_power_system_input_apcpdu',
            title: 'Power Systems Input - APC Schneider Electric PDU',
            poller: 'snmp',
            inherits: null,
            id: 242,
         },
         {
            name: 'cdt_power_system_input_apcups',
            title: 'Power Systems Input - APC Schneider Electric UPS',
            poller: 'snmp',
            inherits: ['cdt_power_system_input'],
            id: 243,
         },
         {
            name: 'cdt_power_system_input_generic_ups',
            title: 'Power Systems Input - Generic UPS',
            poller: 'snmp',
            inherits: ['cdt_power_system_input'],
            id: 244,
         },
         {
            name: 'cdt_power_system_output',
            title: 'Power Systems - Output',
            poller: 'snmp',
            inherits: null,
            id: 245,
         },
         {
            name: 'cdt_power_system_output_alpha',
            title: 'Power Systems Output - Argus/Alpha',
            poller: 'snmp',
            inherits: ['cdt_power_system_output'],
            id: 246,
         },
         {
            name: 'cdt_power_system_output_apcpdu',
            title: 'Power Systems Output - APC Schneider Electric PDU',
            poller: 'snmp',
            inherits: null,
            id: 247,
         },
         {
            name: 'cdt_power_system_output_apcups',
            title: 'Power Systems Output - APC Schneider Electric UPS',
            poller: 'snmp',
            inherits: ['cdt_power_system_output'],
            id: 248,
         },
         {
            name: 'cdt_power_system_output_generic_ups',
            title: 'Power Systems Output - Generic UPS',
            poller: 'snmp',
            inherits: ['cdt_power_system_output'],
            id: 249,
         },
         {
            name: 'cdt_power_system_status',
            title: 'Power Systems - Status',
            poller: 'snmp',
            inherits: null,
            id: 250,
         },
         {
            name: 'cdt_power_system_status_alpha',
            title: 'Power Systems Status - Alpha Power',
            poller: 'snmp',
            inherits: ['cdt_power_system_status'],
            id: 251,
         },
         {
            name: 'cdt_power_system_status_apcpdu',
            title: 'Power Systems Status - APC Schneider Electric PDU',
            poller: 'snmp',
            inherits: ['cdt_power_system_status'],
            id: 252,
         },
         {
            name: 'cdt_power_system_status_apcups',
            title: 'Power Systems Status - APC Schneider Electric UPS',
            poller: 'snmp',
            inherits: ['cdt_power_system_status'],
            id: 253,
         },
         {
            name: 'cdt_power_system_status_generic_ups',
            title: 'Power Systems Status - Generic UPS',
            poller: 'snmp',
            inherits: ['cdt_power_system_status'],
            id: 254,
         },
         {
            name: 'cdt_power_volts_sensor',
            title: 'Sensor - Power - Volts',
            poller: 'snmp',
            inherits: null,
            id: 255,
         },
         {
            name: 'cdt_power_volts_sensor_cisco',
            title: 'Sensor - Power - Volts - Cisco',
            poller: 'snmp',
            inherits: ['cdt_power_volts_sensor'],
            id: 256,
         },
         {
            name: 'cdt_power_volts_sensor_entity',
            title: 'Sensor - Power - Volts - Entity',
            poller: 'snmp',
            inherits: ['cdt_power_volts_sensor'],
            id: 257,
         },
         {
            name: 'cdt_power_watts_sensor',
            title: 'Sensor - Power - Watts',
            poller: 'snmp',
            inherits: null,
            id: 258,
         },
         {
            name: 'cdt_power_watts_sensor_cisco',
            title: 'Sensor - Power - Watts - Cisco',
            poller: 'snmp',
            inherits: ['cdt_power_watts_sensor'],
            id: 259,
         },
         {
            name: 'cdt_power_watts_sensor_entity',
            title: 'Sensor - Power - Watts - Entity',
            poller: 'snmp',
            inherits: ['cdt_power_watts_sensor'],
            id: 260,
         },
         {
            name: 'cdt_printer',
            title: 'Printer',
            poller: 'snmp',
            inherits: null,
            id: 261,
         },
         {
            name: 'cdt_printer_general',
            title: 'Printer - General',
            poller: 'snmp',
            inherits: ['cdt_printer'],
            id: 262,
         },
         {
            name: 'cdt_process_table',
            title: 'Process Details',
            poller: 'spe-proc-monitor',
            inherits: null,
            id: 263,
         },
         {
            name: 'cdt_ranges',
            title: 'Custom Data Type Ranges',
            poller: null,
            inherits: null,
            id: 264,
         },
         {
            name: 'cdt_sonicwall_vpn_users',
            title: 'SonicWall VPN Users',
            poller: 'snmp',
            inherits: null,
            id: 265,
         },
         {
            name: 'cdt_t128_peer',
            title: '128T Router Peers',
            poller: 'snmp',
            inherits: null,
            id: 266,
         },
         {
            name: 'cdt_temperature',
            title: 'Temperature',
            poller: 'snmp',
            inherits: null,
            id: 267,
         },
         {
            name: 'cdt_temperature_alcatel',
            title: 'Temperature - Alcatel',
            poller: 'snmp',
            inherits: ['cdt_temperature'],
            id: 268,
         },
         {
            name: 'cdt_temperature_alcatel_aos7',
            title: 'Temperature - Alcatel - AOS7',
            poller: 'snmp',
            inherits: ['cdt_temperature'],
            id: 269,
         },
         {
            name: 'cdt_temperature_apc_env',
            title: 'Temperature - APC',
            poller: 'snmp',
            inherits: ['cdt_temperature'],
            id: 270,
         },
         {
            name: 'cdt_temperature_apc_int',
            title: 'Temperature - APC Internal',
            poller: 'snmp',
            inherits: ['cdt_temperature'],
            id: 271,
         },
         {
            name: 'cdt_temperature_avaya_s5',
            title: 'Temperature - Avaya - S5',
            poller: 'snmp',
            inherits: ['cdt_temperature'],
            id: 272,
         },
         {
            name: 'cdt_temperature_cisco',
            title: 'Temperature - Cisco',
            poller: 'snmp',
            inherits: ['cdt_temperature'],
            id: 273,
         },
         {
            name: 'cdt_temperature_dell_F10_S',
            title: 'Temperature - Dell F10 S',
            poller: 'snmp',
            inherits: ['cdt_temperature'],
            id: 274,
         },
         {
            name: 'cdt_temperature_dell_dnos',
            title: 'Temperature - Dell DNOS',
            poller: 'snmp',
            inherits: ['cdt_temperature'],
            id: 275,
         },
         {
            name: 'cdt_temperature_dell_power',
            title: 'Temperature - Dell PowerConnect',
            poller: 'snmp',
            inherits: ['cdt_temperature'],
            id: 276,
         },
         {
            name: 'cdt_temperature_extreme',
            title: 'Temperature - Extreme',
            poller: 'snmp',
            inherits: ['cdt_temperature'],
            id: 277,
         },
         {
            name: 'cdt_temperature_extreme_vsp',
            title: 'Temperature - Extreme VSP',
            poller: 'snmp',
            inherits: ['cdt_temperature'],
            id: 278,
         },
         {
            name: 'cdt_temperature_foundry',
            title: 'Temperature - Foundry',
            poller: 'snmp',
            inherits: ['cdt_temperature'],
            id: 279,
         },
         {
            name: 'cdt_temperature_foundry_mlx',
            title: 'Temperature - Foundry MLX',
            poller: 'snmp',
            inherits: ['cdt_temperature_foundry', 'cdt_temperature'],
            id: 280,
         },
         {
            name: 'cdt_temperature_juniper',
            title: 'Temperature - Juniper',
            poller: 'snmp',
            inherits: ['cdt_temperature'],
            id: 281,
         },
         {
            name: 'cdt_temperature_netscreen',
            title: 'Temperature - Netscreen',
            poller: 'snmp',
            inherits: ['cdt_temperature'],
            id: 282,
         },
         {
            name: 'cdt_temperature_sensor',
            title: 'Temperature - Sensor',
            poller: 'snmp',
            inherits: ['cdt_temperature'],
            id: 283,
         },
         {
            name: 'cdt_temperature_sensor_cisco',
            title: 'Temperature - Cisco Sensor',
            poller: 'snmp',
            inherits: ['cdt_temperature'],
            id: 284,
         },
         {
            name: 'cdt_ubiquiti_airmax',
            title: 'Ubiquiti AirMAX',
            poller: 'snmp',
            inherits: null,
            id: 285,
         },
         {
            name: 'cdt_ubiquiti_radio',
            title: 'Ubiquiti Radio',
            poller: 'snmp',
            inherits: null,
            id: 286,
         },
         {
            name: 'cdt_ubiquiti_wl_stats',
            title: 'Ubiquiti Wireless Statistics',
            poller: 'snmp',
            inherits: null,
            id: 287,
         },
         {
            name: 'cdt_ups',
            title: 'UPS',
            poller: 'snmp',
            inherits: null,
            id: 288,
         },
         {
            name: 'cdt_ups_apc',
            title: 'UPS - APC',
            poller: 'snmp',
            inherits: ['cdt_ups'],
            id: 289,
         },
         {
            name: 'cdt_ups_generic',
            title: 'UPS - Generic',
            poller: 'snmp',
            inherits: ['cdt_ups'],
            id: 290,
         },
         {
            name: 'cdt_waas_cisco',
            title: 'Cisco WAAS',
            poller: 'snmp',
            inherits: null,
            id: 291,
         },
         {
            name: 'cdt_wireless_ap',
            title: 'Wireless AP',
            poller: 'snmp',
            inherits: null,
            id: 292,
         },
         {
            name: 'cdt_wireless_ap_cisco',
            title: 'Wireless AP - Cisco',
            poller: 'snmp',
            inherits: ['cdt_wireless_ap'],
            id: 293,
         },
         {
            name: 'cdt_wireless_ap_extreme',
            title: 'Wireless AP - Extreme',
            poller: 'snmp',
            inherits: ['cdt_wireless_ap'],
            id: 294,
         },
         {
            name: 'cdt_wlc_cisco_ap',
            title: 'WLC - Cisco AP',
            poller: 'snmp',
            inherits: null,
            id: 295,
         },
         {
            name: 'cdt_wlc_cisco_ap_cdp',
            title: 'WLC - Cisco AP CDP',
            poller: 'snmp',
            inherits: null,
            id: 296,
         },
         {
            name: 'cdt_wlc_cisco_ap_if',
            title: 'WLC - Cisco AP Interfaces',
            poller: 'snmp',
            inherits: null,
            id: 297,
         },
         {
            name: 'config_build',
            title: 'Configuration Build',
            poller: null,
            inherits: null,
            id: 298,
         },
         {
            name: 'dashboard_panel_template',
            title: 'Statseeker Dashboard Panel Template',
            poller: null,
            inherits: null,
            id: 299,
         },
         {
            name: 'discover',
            title: 'Discover',
            poller: null,
            inherits: null,
            id: 300,
         },
         {
            name: 'discover_config',
            title: 'Discover Configuration',
            poller: null,
            inherits: null,
            id: 301,
         },
         {
            name: 'discover_history',
            title: 'Discover History',
            poller: null,
            inherits: null,
            id: 302,
         },
         {
            name: 'discover_hosts',
            title: 'Discover Hosts',
            poller: null,
            inherits: null,
            id: 303,
         },
         {
            name: 'entity',
            title: 'Statseeker Entities',
            poller: null,
            inherits: null,
            id: 304,
         },
         {
            name: 'event',
            title: 'Event Entity Details',
            poller: null,
            inherits: null,
            id: 305,
         },
         {
            name: 'event_record',
            title: 'Events',
            poller: null,
            inherits: null,
            id: 306,
         },
         {
            name: 'field',
            title: 'Field',
            poller: null,
            inherits: null,
            id: 307,
         },
         {
            name: 'group',
            title: 'Group',
            poller: null,
            inherits: null,
            id: 308,
         },
         {
            name: 'ip_range_config',
            title: 'IP Range Configuration',
            poller: null,
            inherits: null,
            id: 309,
         },
         {
            name: 'irc_to_sc_map',
            title: 'IP Range Configuration to SNMP Credential Map',
            poller: null,
            inherits: null,
            id: 310,
         },
         {
            name: 'license',
            title: 'License',
            poller: null,
            inherits: null,
            id: 311,
         },
         {
            name: 'link',
            title: 'API Links',
            poller: null,
            inherits: null,
            id: 312,
         },
         {
            name: 'mac',
            title: 'MAC Records',
            poller: null,
            inherits: null,
            id: 313,
         },
         {
            name: 'message',
            title: 'Message',
            poller: null,
            inherits: null,
            id: 314,
         },
         {
            name: 'mis_record',
            title: 'MAC-IP Records',
            poller: null,
            inherits: null,
            id: 315,
         },
         {
            name: 'nim_options',
            title: 'NIM Options',
            poller: null,
            inherits: null,
            id: 316,
         },
         {
            name: 'notification',
            title: 'Notifications',
            poller: null,
            inherits: null,
            id: 317,
         },
         {
            name: 'oa_application',
            title: 'OA Application',
            poller: null,
            inherits: null,
            id: 318,
         },
         {
            name: 'oa_component',
            title: 'OA Component',
            poller: null,
            inherits: null,
            id: 319,
         },
         {
            name: 'oa_component_service',
            title: 'OA Component Service',
            poller: null,
            inherits: null,
            id: 320,
         },
         {
            name: 'oa_filelist',
            title: 'Component Filelist',
            poller: null,
            inherits: null,
            id: 321,
         },
         {
            name: 'oa_service',
            title: 'Distributable Service',
            poller: null,
            inherits: null,
            id: 322,
         },
         {
            name: 'object',
            title: 'Object',
            poller: null,
            inherits: null,
            id: 323,
         },
         {
            name: 'report',
            title: 'Report Configuration',
            poller: null,
            inherits: null,
            id: 324,
         },
         {
            name: 'snmp_credential',
            title: 'SNMP Credential Details',
            poller: null,
            inherits: null,
            id: 325,
         },
         {
            name: 'spe_aci',
            title: 'APIC Configurations',
            poller: null,
            inherits: null,
            id: 326,
         },
         {
            name: 'syslog',
            title: 'Syslog',
            poller: null,
            inherits: null,
            id: 327,
         },
         {
            name: 'task',
            title: 'Task',
            poller: null,
            inherits: null,
            id: 328,
         },
         {
            name: 'threshold',
            title: 'Threshold Configuration',
            poller: null,
            inherits: null,
            id: 329,
         },
         {
            name: 'threshold_event',
            title: 'Threshold Entity Details',
            poller: null,
            inherits: null,
            id: 330,
         },
         {
            name: 'threshold_record',
            title: 'Threshold Events',
            poller: null,
            inherits: null,
            id: 331,
         },
         {
            name: 'timefilter',
            title: 'Time Filter',
            poller: null,
            inherits: null,
            id: 332,
         },
         {
            name: 'trap',
            title: 'Trap',
            poller: null,
            inherits: null,
            id: 333,
         },
         {
            name: 'user',
            title: 'User',
            poller: null,
            inherits: null,
            id: 334,
         },
      ],
      describe: null,
   };
}
