/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as InterfacesImport } from './routes/interfaces'
import { Route as DevicesImport } from './routes/devices'
import { Route as SNMPEntityImport } from './routes/snmp_entities'
import { Route as OAManagerImport } from './routes/oa_manager'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const InterfacesRoute = InterfacesImport.update({
  path: '/interfaces',
  getParentRoute: () => rootRoute,
} as any)

const DevicesRoute = DevicesImport.update({
  path: '/devices',
  getParentRoute: () => rootRoute,
} as any)

const SNMPEntityRoute = SNMPEntityImport.update({
  path: '/snmp_entities',
  getParentRoute: () => rootRoute,
} as any)

const OAManagerRoute = OAManagerImport.update({
  path: '/oa_manager',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/snmp_entities': {
      id: '/snmp_entities'
      path: '/snmp_entities'
      fullPath: '/snmp_entities'
      preLoaderRoute: typeof SNMPEntityImport
      parentRoute: typeof rootRoute
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesImport
      parentRoute: typeof rootRoute
    }
    '/interfaces': {
      id: '/interfaces'
      path: '/interfaces'
      fullPath: '/interfaces'
      preLoaderRoute: typeof InterfacesImport
      parentRoute: typeof rootRoute
    },
    '/oa_manager': {
      id: '/oa_manager'
      path: '/oa_manager'
      fullPath: '/oa_manager'
      preLoaderRoute: typeof OAManagerImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  SNMPEntityRoute,
  DevicesRoute,
  InterfacesRoute,
  OAManagerRoute
})

/* prettier-ignore-end */
