/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ScheduleImport } from './routes/schedule'
import { Route as PingdiscoverImport } from './routes/ping_discover'
import { Route as HistoryImport } from './routes/history'
import { Route as CurrentImport } from './routes/current'
import { Route as DiscoveryImport } from './routes/_discovery'
import { Route as IndexImport } from './routes/index'
import { Route as ProgressIdImport } from './routes/progress.$id'
import { Route as DiscoveryRewalkImport } from './routes/_discovery.rewalk'
import { Route as DiscoveryPingImport } from './routes/_discovery.ping'
import { Route as DiscoveryNetworkImport } from './routes/_discovery.network'
import { Route as DiscoveryManualImport } from './routes/_discovery.manual'

// Create/Update Routes

const ScheduleRoute = ScheduleImport.update({
  path: '/schedule',
  getParentRoute: () => rootRoute,
} as any)

const PingdiscoverRoute = PingdiscoverImport.update({
  path: '/ping_discover',
  getParentRoute: () => rootRoute,
} as any)

const HistoryRoute = HistoryImport.update({
  path: '/history',
  getParentRoute: () => rootRoute,
} as any)

const CurrentRoute = CurrentImport.update({
  path: '/current',
  getParentRoute: () => rootRoute,
} as any)

const DiscoveryRoute = DiscoveryImport.update({
  id: '/_discovery',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProgressIdRoute = ProgressIdImport.update({
  path: '/progress/$id',
  getParentRoute: () => rootRoute,
} as any)

const DiscoveryRewalkRoute = DiscoveryRewalkImport.update({
  path: '/rewalk',
  getParentRoute: () => DiscoveryRoute,
} as any)

const DiscoveryPingRoute = DiscoveryPingImport.update({
  path: '/ping',
  getParentRoute: () => DiscoveryRoute,
} as any)

const DiscoveryNetworkRoute = DiscoveryNetworkImport.update({
  path: '/network',
  getParentRoute: () => DiscoveryRoute,
} as any)

const DiscoveryManualRoute = DiscoveryManualImport.update({
  path: '/manual',
  getParentRoute: () => DiscoveryRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_discovery': {
      id: '/_discovery'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DiscoveryImport
      parentRoute: typeof rootRoute
    }
    '/current': {
      id: '/current'
      path: '/current'
      fullPath: '/current'
      preLoaderRoute: typeof CurrentImport
      parentRoute: typeof rootRoute
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryImport
      parentRoute: typeof rootRoute
    }
    '/ping_discover': {
      id: '/ping_discover'
      path: '/ping_discover'
      fullPath: '/ping_discover'
      preLoaderRoute: typeof PingdiscoverImport
      parentRoute: typeof rootRoute
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleImport
      parentRoute: typeof rootRoute
    }
    '/_discovery/manual': {
      id: '/_discovery/manual'
      path: '/manual'
      fullPath: '/manual'
      preLoaderRoute: typeof DiscoveryManualImport
      parentRoute: typeof DiscoveryImport
    }
    '/_discovery/network': {
      id: '/_discovery/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof DiscoveryNetworkImport
      parentRoute: typeof DiscoveryImport
    }
    '/_discovery/ping': {
      id: '/_discovery/ping'
      path: '/ping'
      fullPath: '/ping'
      preLoaderRoute: typeof DiscoveryPingImport
      parentRoute: typeof DiscoveryImport
    }
    '/_discovery/rewalk': {
      id: '/_discovery/rewalk'
      path: '/rewalk'
      fullPath: '/rewalk'
      preLoaderRoute: typeof DiscoveryRewalkImport
      parentRoute: typeof DiscoveryImport
    }
    '/progress/$id': {
      id: '/progress/$id'
      path: '/progress/$id'
      fullPath: '/progress/$id'
      preLoaderRoute: typeof ProgressIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  DiscoveryRoute.addChildren([
    DiscoveryManualRoute,
    DiscoveryNetworkRoute,
    DiscoveryPingRoute,
    DiscoveryRewalkRoute,
  ]),
  CurrentRoute,
  HistoryRoute,
  PingdiscoverRoute,
  ScheduleRoute,
  ProgressIdRoute,
])

/* prettier-ignore-end */
