/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CredentialsImport } from './routes/_credentials'
import { Route as CredentialsIndexImport } from './routes/_credentials.index'
import { Route as CredentialsDeleteImport } from './routes/_credentials.delete'
import { Route as CredentialsAddImport } from './routes/_credentials.add'
import { Route as CredentialsEditIdImport } from './routes/_credentials.edit.$id'
import { Route as CredentialsCopyIdImport } from './routes/_credentials.copy.$id'

// Create/Update Routes

const CredentialsRoute = CredentialsImport.update({
  id: '/_credentials',
  getParentRoute: () => rootRoute,
} as any)

const CredentialsIndexRoute = CredentialsIndexImport.update({
  path: '/',
  getParentRoute: () => CredentialsRoute,
} as any)

const CredentialsDeleteRoute = CredentialsDeleteImport.update({
  path: '/delete',
  getParentRoute: () => CredentialsRoute,
} as any)

const CredentialsAddRoute = CredentialsAddImport.update({
  path: '/add',
  getParentRoute: () => CredentialsRoute,
} as any)

const CredentialsEditIdRoute = CredentialsEditIdImport.update({
  path: '/edit/$id',
  getParentRoute: () => CredentialsRoute,
} as any)

const CredentialsCopyIdRoute = CredentialsCopyIdImport.update({
  path: '/copy/$id',
  getParentRoute: () => CredentialsRoute,
} as any)


// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_credentials': {
      id: '/_credentials'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof CredentialsImport
      parentRoute: typeof rootRoute
    }
    '/_credentials/add': {
      id: '/_credentials/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof CredentialsAddImport
      parentRoute: typeof CredentialsImport
    }
    '/_credentials/delete': {
      id: '/_credentials/delete'
      path: '/delete'
      fullPath: '/delete'
      preLoaderRoute: typeof CredentialsDeleteImport
      parentRoute: typeof CredentialsImport
    }
    '/_credentials/': {
      id: '/_credentials/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof CredentialsIndexImport
      parentRoute: typeof CredentialsImport
    }
    '/_credentials/copy/$id': {
      id: '/_credentials/copy/$id'
      path: '/copy/$id'
      fullPath: '/copy/$id'
      preLoaderRoute: typeof CredentialsCopyIdImport
      parentRoute: typeof CredentialsImport
    }
    '/_credentials/edit/$id': {
      id: '/_credentials/edit/$id'
      path: '/edit/$id'
      fullPath: '/edit/$id'
      preLoaderRoute: typeof CredentialsEditIdImport
      parentRoute: typeof CredentialsImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  CredentialsRoute: CredentialsRoute.addChildren({
    CredentialsAddRoute,
    CredentialsDeleteRoute,
    CredentialsIndexRoute,
    CredentialsCopyIdRoute,
    CredentialsEditIdRoute,
  }),
})

/* prettier-ignore-end */
