/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TerminalsImport } from './routes/terminals'
import { Route as ScreeningPointsImport } from './routes/screeningPoints'
import { Route as NetworksImport } from './routes/networks'
import { Route as LanesImport } from './routes/lanes'
import { Route as EquipmentsImport } from './routes/equipments'
import { Route as CertificatesImport } from './routes/certificates'
import { Route as AirportsImport } from './routes/airports'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TerminalsRoute = TerminalsImport.update({
  path: '/terminals',
  getParentRoute: () => rootRoute,
} as any)

const ScreeningPointsRoute = ScreeningPointsImport.update({
  path: '/screeningPoints',
  getParentRoute: () => rootRoute,
} as any)

const NetworksRoute = NetworksImport.update({
  path: '/networks',
  getParentRoute: () => rootRoute,
} as any)

const LanesRoute = LanesImport.update({
  path: '/lanes',
  getParentRoute: () => rootRoute,
} as any)

const EquipmentsRoute = EquipmentsImport.update({
  path: '/equipments',
  getParentRoute: () => rootRoute,
} as any)

const CertificatesRoute = CertificatesImport.update({
  path: '/certificates',
  getParentRoute: () => rootRoute,
} as any)

const AirportsRoute = AirportsImport.update({
  path: '/airports',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/airports': {
      id: '/airports'
      path: '/airports'
      fullPath: '/airports'
      preLoaderRoute: typeof AirportsImport
      parentRoute: typeof rootRoute
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesImport
      parentRoute: typeof rootRoute
    }
    '/equipments': {
      id: '/equipments'
      path: '/equipments'
      fullPath: '/equipments'
      preLoaderRoute: typeof EquipmentsImport
      parentRoute: typeof rootRoute
    }
    '/lanes': {
      id: '/lanes'
      path: '/lanes'
      fullPath: '/lanes'
      preLoaderRoute: typeof LanesImport
      parentRoute: typeof rootRoute
    }
    '/networks': {
      id: '/networks'
      path: '/networks'
      fullPath: '/networks'
      preLoaderRoute: typeof NetworksImport
      parentRoute: typeof rootRoute
    }
    '/screeningPoints': {
      id: '/screeningPoints'
      path: '/screeningPoints'
      fullPath: '/screeningPoints'
      preLoaderRoute: typeof ScreeningPointsImport
      parentRoute: typeof rootRoute
    }
    '/terminals': {
      id: '/terminals'
      path: '/terminals'
      fullPath: '/terminals'
      preLoaderRoute: typeof TerminalsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  AirportsRoute,
  CertificatesRoute,
  EquipmentsRoute,
  LanesRoute,
  NetworksRoute,
  ScreeningPointsRoute,
  TerminalsRoute,
})

/* prettier-ignore-end */
