import { type ApiResponse } from '../../types';
import { type APILicense } from './type';

export async function getLicenseMock() {
   return new Promise<ApiResponse<APILicense>>((resolve) => {
      setTimeout(() => {
         resolve({
            success: true,
            errcode: 0,
            errmsg: 'ok',
            time: 1721696923,
            sequence: 2,
            data_total: 1,
            data: [
               {
                  id: 1,
                  version: '25.2.0.2508220117',
                  server_id: '300-003',
                  hardware_id: '187750808714114:1930701052:251774331891406',
                  tier: 'Statseeker Enterprise',
                  licenced: true,
                  perpetual: false,
                  not_before: 1755871200,
                  not_after: 1771768800,
                  features: [
                     {
                        name: 'ping',
                        title: 'Ping Polling',
                        description: 'Allows ping polling',
                        visibility: 'visible',
                        not_before: null,
                        not_after: null,
                        enabled: true,
                        licenced: true,
                        limits: [
                           {
                              name: 'device',
                              title: 'Ping polled devices',
                              description: 'The maximum number of devices that can be ping polled',
                              visibility: 'visible',
                              limit: 10000,
                              polled: 0,
                              exceeded: 0,
                              total: 1,
                           },
                           {
                              name: 'oa',
                              title: 'OA ping pollers',
                              description:
                                 'The maximum number of observability appliances that can be used for ping polling',
                              visibility: 'visible',
                              limit: 0,
                              polled: 0,
                              exceeded: 0,
                              total: 0,
                           },
                        ],
                     },
                     {
                        name: 'snmp',
                        title: 'SNMP Polling',
                        description: 'Allows SNMP polling',
                        visibility: 'visible',
                        not_before: null,
                        not_after: null,
                        enabled: true,
                        licenced: true,
                        limits: [
                           {
                              name: 'device',
                              title: 'SNMP polled devices',
                              description: 'The maximum number of devices that can be SNMP polled',
                              visibility: 'visible',
                              limit: 10000,
                              polled: 0,
                              exceeded: 0,
                              total: 1,
                           },
                           {
                              name: 'port',
                              title: 'SNMP polled interfaces',
                              description:
                                 'The maximum number of interfaces that can be SNMP polled',
                              visibility: 'visible',
                              limit: 1000000,
                              polled: 0,
                              exceeded: 0,
                              total: 0,
                           },
                           {
                              name: 'oa',
                              title: 'OA SNMP pollers',
                              description:
                                 'The maximum number of observability appliances that can be used for SNMP polling',
                              visibility: 'visible',
                              limit: 0,
                              polled: 0,
                              exceeded: 0,
                              total: 0,
                           },
                        ],
                     },
                     {
                        name: 'aci',
                        title: 'ACI',
                        description: 'Cisco ACI',
                        visibility: 'visible',
                        not_before: null,
                        not_after: null,
                        enabled: false,
                        licenced: false,
                        limits: [
                           {
                              name: 'apic',
                              title: 'APIC limit',
                              description:
                                 'The maximum number of APIC devices that can be configured',
                              visibility: 'visible',
                              limit: 0,
                              polled: 0,
                              exceeded: 0,
                              total: 0,
                           },
                        ],
                     },
                     {
                        name: 'kafka',
                        title: 'Kafka Data Exporter',
                        description: 'Allows exporting of API data to a Kafka message bus',
                        visibility: 'conditional',
                        not_before: null,
                        not_after: null,
                        enabled: false,
                        licenced: false,
                        limits: [],
                     },
                     {
                        name: 'meraki',
                        title: 'Meraki Observability',
                        description: 'Meraki observability feature',
                        visibility: 'visible',
                        not_before: null,
                        not_after: null,
                        enabled: false,
                        licenced: false,
                        limits: [],
                     },
                     {
                        name: 'xplore',
                        title: 'Xplore',
                        description: 'Xplore feature',
                        visibility: 'conditional',
                        not_before: null,
                        not_after: null,
                        enabled: true,
                        licenced: true,
                        limits: [
                           {
                              name: 'cpe',
                              title: 'CPE limit',
                              description:
                                 'The maximum number of CPE devices that can be discovered',
                              visibility: 'conditional',
                              limit: 0,
                              polled: 0,
                              exceeded: 0,
                              total: 0,
                           },
                        ],
                     },
                     {
                        name: 'analytics',
                        title: 'Analytics reporting',
                        description: 'Analytics',
                        visibility: 'hidden',
                        not_before: null,
                        not_after: null,
                        enabled: true,
                        licenced: true,
                        limits: [],
                     },
                     {
                        name: 'analytics.anomaly',
                        title: 'Anomaly Detection / Baselines',
                        description: 'Anomaly Detection',
                        visibility: 'visible',
                        not_before: null,
                        not_after: null,
                        enabled: true,
                        licenced: true,
                        limits: [],
                     },
                     {
                        name: 'analytics.forecast',
                        title: 'Forecasting',
                        description: 'Forecasting feature status',
                        visibility: 'visible',
                        not_before: null,
                        not_after: null,
                        enabled: true,
                        licenced: true,
                        limits: [],
                     },
                     {
                        name: 'analytics.trend',
                        title: 'Trendlines',
                        description: 'Trendline feature status',
                        visibility: 'visible',
                        not_before: null,
                        not_after: null,
                        enabled: true,
                        licenced: true,
                        limits: [],
                     },
                     {
                        name: 'ha',
                        title: 'High Availability',
                        description: 'High Availability',
                        visibility: 'conditional',
                        not_before: null,
                        not_after: null,
                        limits: [],
                        enabled: true,
                        licenced: true,
                     },
                     {
                        name: 'rest_api',
                        title: 'REST API',
                        description: 'Allows the use of the Statseeker REST API',
                        visibility: 'hidden',
                        not_before: null,
                        not_after: null,
                        limits: [],
                        enabled: true,
                        licenced: true,
                     },
                     {
                        name: 'rest_api.read',
                        title: 'REST API Read',
                        description: 'Allows read access to the Statseeker REST API',
                        visibility: 'visible',
                        not_before: null,
                        not_after: null,
                        limits: [],
                        enabled: true,
                        licenced: true,
                     },
                     {
                        name: 'rest_api.write',
                        title: 'REST API Write',
                        description: 'Allows write access to the Statseeker REST API',
                        visibility: 'visible',
                        not_before: null,
                        not_after: null,
                        limits: [],
                        enabled: true,
                        licenced: true,
                     },
                     {
                        name: 'upstream_devices',
                        title: 'Upstream Devices',
                        description: 'Allows upstream devices to be configured',
                        visibility: 'visible',
                        not_before: null,
                        not_after: null,
                        limits: [],
                        enabled: false,
                        licenced: false,
                     },
                     {
                        name: 'alert_webhooks',
                        title: 'Alerting Webhooks',
                        description: 'Allows webhooks to be used with alerting',
                        visibility: 'visible',
                        not_before: null,
                        limits: [],
                        not_after: null,
                        enabled: false,
                        licenced: false,
                     },
                  ],
               },
            ],
         });
      }, 1000);
   });
}
