/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DeleteImport } from './routes/delete'
import { Route as AddImport } from './routes/add'
import { Route as IndexImport } from './routes'
import { Route as EditIdImport } from './routes/edit.$id'
import { Route as CopyIdImport } from './routes/copy.$id'

// Create/Update Routes

const DeleteRoute = DeleteImport.update({
  path: '/delete',
  getParentRoute: () => rootRoute,
} as any)

const AddRoute = AddImport.update({
  path: '/add',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const EditIdRoute = EditIdImport.update({
  path: '/edit/$id',
  getParentRoute: () => rootRoute,
} as any)

const CopyIdRoute = CopyIdImport.update({
  path: '/copy/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddImport
      parentRoute: typeof rootRoute
    }
    '/delete': {
      id: '/delete'
      path: '/delete'
      fullPath: '/delete'
      preLoaderRoute: typeof DeleteImport
      parentRoute: typeof rootRoute
    }
    '/copy/$id': {
      id: '/copy/$id'
      path: '/copy/$id'
      fullPath: '/copy/$id'
      preLoaderRoute: typeof CopyIdImport
      parentRoute: typeof rootRoute
    }
    '/edit/$id': {
      id: '/edit/$id'
      path: '/edit/$id'
      fullPath: '/edit/$id'
      preLoaderRoute: typeof EditIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  AddRoute,
  DeleteRoute,
  CopyIdRoute,
  EditIdRoute,
})

/* prettier-ignore-end */
